INSERT INTO deals (deal_name,responsable,potencial,product_type,email,fecha_envio,seguimiento_1,seguimiento_2,seguimiento_3,feedback,status) VALUES
  ('Maye','Angeles','Grupo Iberebro','Buy to Rent',NULL,'2025-05-12',NULL,NULL,NULL,'Lo tiene en mente','Con feedback'),
  ('Maye','Angeles','Omega Capital','Buy to Rent',NULL,'2025-05-13',NULL,NULL,NULL,'No contestan','Descartado'),
  ('Maye','Angeles','Asua inversiones','Buy to Rent',NULL,'2025-05-13',NULL,NULL,NULL,'No contestan','Descartado'),
  ('Maye','Angeles','Tenigla','Buy to Rent',NULL,'2025-05-13',NULL,NULL,NULL,'No contestan','Descartado'),
  ('Maye','Angeles','Caboel','Buy to Rent',NULL,'2025-05-13',NULL,NULL,NULL,'No encaja en nuestros actuales objetivos de inversión.','Descartado'),
  ('Maye','Angeles','Rentatur','Buy to Rent',NULL,'2025-05-13',NULL,NULL,NULL,'Te agradezco la oportunidad, pero ahora mismo no tenemos previsto incrementar nuestra posición en real estate.','Descartado'),
  ('Maye','Alberto','Vivenio','Buy to Rent',NULL,'2025-05-13',NULL,NULL,NULL,'Creo que lo más operativo es hablar sobre alguna operación en concreto ya que tendría que ser un esquema ad-hoc en todos los casos.','Con feedback'),
  ('Maye','Angeles','Cosentino','Buy to Rent',NULL,'2025-05-13',NULL,NULL,NULL,'Estamos en algún vehículo con estrategia parecida pero más diversificado geográficamente y de momento vamos a cubrir nuestra exposición a BTR desde el mismo.','Con feedback'),
  ('Maye','Angeles','Grupo Timón','Buy to Rent',NULL,'2025-05-16',NULL,NULL,NULL,'Muchas gracias Ángeles, pero en lo que se refiere a RE ahora mismo estamos centrados únicamente en los proyectos que tenemos en curso, especialmente en el segmento de living','Con feedback'),
  ('Maye','Angeles','Testa Homes (Jose Antonio)','Buy to Rent',NULL,'2025-05-20',NULL,NULL,NULL,'Lo hemos comentado en interno y preferimos no avanzar por el mix de producto y localización. Como os comentamos en llamada nuestro foco es el producto residencial y como preferencia de localización Madrid.','Con feedback'),
  ('Maye','Angeles','FO Herrecha','Buy to Rent',NULL,'2025-09-12',NULL,NULL,NULL,'La he estado viendo y por ahora no vamos a avanzar en oportunidades relacionadas con el residencial. Estamos cerrando oportunidades en otras áreas de inmobiliario donde vamos a poner el foco durante 2025.','Descartado'),
  ('Maye','Angeles','Antonio La Calle (Grupo Barcelon)','Flex Linving',NULL,'2025-10-06',NULL,NULL,NULL,'No interesados','Descartado'),
  ('Maye','Angeles','Sebastian Bernasconi','Flex living y Buy to Rent',NULL,'2025-10-14',NULL,NULL,NULL,'No interesados','Descartado'),
  ('Maye','Angeles','Tech Stone (Jose Pedro)','Flex Linving',NULL,'2025-10-14','2025-10-30',NULL,NULL,'Pendiente de recibir algo de info antes de firmar NDA.','Pendiente'),
  ('Maye','Angeles','AEW','Flex living y Buy to Rent',NULL,'2025-10-21','2025-10-30',NULL,NULL,'Tercer y último mail enviado de seguimiento','Con feedback'),
  ('Maye','Angeles','AEXX Capital','Flex living y Buy to Rent',NULL,'2025-10-21','2025-10-30',NULL,NULL,'Tercer y último mail enviado de seguimiento','Con feedback'),
  ('Maye','Angeles','Ibero Capital','Flex living y Buy to Rent',NULL,'2025-10-22',NULL,NULL,NULL,'NDA Firmado y enviada información/ Reunión presencial el 7 noviembre. Les interesan dos activos/ (20/11/2025) Enviado modelo financiero con (Sta Ponca, Major y Medical)','En proceso'),
  ('IPO','Angeles','Asua',NULL,NULL,'2026-04-27',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('IPO','Angeles','Iberebro',NULL,NULL,'2026-04-27',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','María Souto',NULL,NULL,'2025-10-30','2026-02-26',NULL,NULL,'No interesados,','Descartado'),
  ('Arca','Alberto','Inversor (venta local - Luigi)',NULL,NULL,'2025-10-30',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Juan (FO Agerlat)',NULL,NULL,'2025-10-30','2026-02-26','2026-03-12',NULL,'Ahora mismo estamos próximos a cerrar un par de inversiones, por lo que no tenemos capacidad para mucho más.','Descartado'),
  ('Arca','Alberto','David Martín',NULL,NULL,'2025-11-03',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Rosauro Varo',NULL,NULL,'2025-11-03','2026-02-26',NULL,NULL,'No interesados,','Descartado'),
  ('Arca','Angeles','Josep Vera',NULL,NULL,'2025-11-12','2026-02-26','2026-03-12','2026-04-23','No interesados,','Descartado'),
  ('Arca','Angeles','Cosentino',NULL,NULL,'2025-11-12',NULL,NULL,NULL,'No interesados,','Descartado'),
  ('Arca','Angeles','Carlos Pardo (Nostrum Simul)',NULL,NULL,'2025-11-12','2026-02-26',NULL,NULL,'Gracias Ángeles, si hay interés te lo haré saber.','Con feedback'),
  ('Arca','Angeles','Amadasti SL (Clara Aguilera)',NULL,NULL,'2025-11-12','2026-02-26','2026-03-12',NULL,'No interesados,','Descartado'),
  ('Arca','Angeles','Inderhabs',NULL,NULL,'2025-11-12',NULL,NULL,NULL,'No interesados,','Descartado'),
  ('Arca','Angeles','Herrecha (Ismael Valero)',NULL,NULL,'2025-11-12',NULL,NULL,NULL,'Indicarte que actualmente no invertimos en este tipo de vehículos.','Con feedback'),
  ('Arca','Angeles','Jaime Codorniu',NULL,NULL,'2025-11-12',NULL,NULL,NULL,'Hemos cubierto el cupo de este año en el segmento.','Con feedback'),
  ('Arca','Angeles','Spai d''inversiones',NULL,NULL,'2025-11-12',NULL,NULL,NULL,'No interesados,','Descartado'),
  ('Arca','Angeles','Visse Capital',NULL,NULL,'2025-11-12',NULL,NULL,NULL,'Desafortunadamente, no es un producto que nos encaje en estos momentos','Descartado'),
  ('Arca','Angeles','Grupo Alea',NULL,NULL,'2025-11-12','2026-03-12','2026-04-23',NULL,'Call 28 de abril. Finalmente no les encaja','Descartado'),
  ('Arca','Angeles','Petro Nieves (Joan Isac)',NULL,NULL,'2025-11-13','2026-02-04','2026-03-12','2026-04-23','Cerrado por no contestar y hacer 4 contactos.','Descartado'),
  ('Arca','Angeles','Label Investment (Luis)',NULL,NULL,'2025-11-13','2026-03-12',NULL,NULL,'En nuestra estrategia de inversión inmobiliaria, nos limitamos a inversiones o coinversiones directas sobre activos, y descartamos la inversión en vehículos de terceros como regla general.','Con feedback'),
  ('Arca','Andres','Club Inversor Colombia',NULL,NULL,'2025-11-25',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Andres','iCapital',NULL,NULL,'2026-01-15','2026-02-04',NULL,NULL,'Primer contacto y a la espera de feedback','Pendiente'),
  ('Arca','Alberto','Juan Jodar (ofrecido un 1,20%)',NULL,NULL,'2026-01-26',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Aberto','Miguel Angel GBO (ofrecido un 1,20%)',NULL,NULL,'2026-01-26',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Alejandro Carmona',NULL,NULL,'2026-02-04','2026-02-26','2026-03-12',NULL,'No interesados,','Descartado'),
  ('Arca','Angeles','Papanut',NULL,NULL,'2026-02-09','2026-02-26','2026-03-12','2026-04-30','Cerrado por no contestar y hacer 4 contactos.','Descartado'),
  ('Arca','Andres','Devesa',NULL,NULL,'2026-02-09',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Andrés Arencibia',NULL,NULL,'2026-02-10','2026-02-26',NULL,NULL,'Nos reunimos con el y tiene consejo a finales de febrero con Agua de Firgas. Valorará inversión','Con feedback'),
  ('Arca','Angeles','paloma',NULL,NULL,'2026-02-17','2026-03-03','2026-03-10','2026-04-23','Cerrado por no contestar y hacer 4 contactos.','Descartado'),
  ('Arca','Angeles','GBO Juan Carlos',NULL,NULL,'2026-02-17','2026-03-03','2026-03-10','2026-04-23','Cerrado por no contestar y hacer 4 contactos.','Descartado'),
  ('Arca','Aberto','GBO Diego',NULL,NULL,'2026-02-17',NULL,NULL,NULL,'Habló Alberto por telefono con el','Con feedback'),
  ('Arca','Aberto','GBO Garret',NULL,NULL,'2026-02-17',NULL,NULL,NULL,'No interesado. Cruza mails con Alberto el 18/02/26 con la explicación.','Descartado'),
  ('Arca','Aberto','GBO Miguel Angel',NULL,NULL,'2026-02-17',NULL,NULL,NULL,'Habló Alberto por telefono con el','Con feedback'),
  ('Arca','Aberto','GBO Jose Luis',NULL,NULL,'2026-02-17','2026-03-03','2026-03-10',NULL,'Enviado deck y pte, cerrar call','Con feedback'),
  ('Arca','Aberto','GBO Enrique',NULL,NULL,'2026-02-17',NULL,NULL,NULL,'Quiere hablar con nosotro por si nos puede echar una mano','Con feedback'),
  ('Arca','Angeles','Iberfind (Franco)',NULL,NULL,'2026-02-23',NULL,NULL,NULL,'Por el momento no hacemos inversiones con este tipo de vehículos. Preferimos la inversión directa donde nosotros mismos gestionamos los edificios.','Con feedback'),
  ('Arca','Angeles','Grupo Patrimonial Actur (javier) Pte. BBDD Madre ''jpalacio@gpactur.com''',NULL,NULL,'2026-02-23','2026-03-04','2026-04-23','Inivtacion desayuno y cierre',NULL,'Sin respuesta'),
  ('Arca','Angeles','Grupo PMB /Agata) Pte. BBDD Madre',NULL,NULL,'2026-02-23','2026-03-04','2026-04-23',NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Alex Ibañez Viros Capital',NULL,NULL,'2026-02-23','2026-03-04','2026-04-23',NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Andrés Vallejo',NULL,NULL,'2026-02-23','2026-03-04','11/05/2026 Invitación al desayuno',NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Bernardo Ubago',NULL,NULL,'2026-02-23',NULL,NULL,NULL,'Todo el inmobiliario lo hacemos de manera directa, solos o con socios pero directamente','Con feedback'),
  ('Arca','Angeles','Akre Partners (Borja Cabeza)',NULL,NULL,'2026-02-23','2026-03-04',NULL,NULL,'Ahora no invierten','Con feedback'),
  ('Arca','Angeles','Trust Invest (Christian Gallo)',NULL,NULL,'2026-02-23','2026-03-04',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Global Income ( Gonzalo Hortal)',NULL,NULL,'2026-02-23','2026-03-04',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Gaudi Mar (Ignacio Pancorbo)',NULL,NULL,'2026-02-23','2026-03-04',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Javier Gimeno (jgimeno22@outlook.com)  FO Confidencial Pte. BBDD Madre',NULL,NULL,'2026-02-23','2026-03-04',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Vatena (José María)',NULL,NULL,'2026-02-23','2026-03-04',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Spanish Vanity (Juan Garcia) Pte. BBDD Madre',NULL,NULL,'2026-02-23','2026-03-04',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Miguel Vera Pte. BBDD Madre',NULL,NULL,'2026-02-23','2026-03-04','2026-04-14',NULL,NULL,'Sin respuesta'),
  ('Arca','Andres','NX Block Trade',NULL,NULL,'2026-02-22',NULL,NULL,'Reunión virtual y a la espera de feedback','No invierten porque no es un activo core para su portafolio','Con feedback'),
  ('Arca','Angeles','Samuel Pimentel',NULL,NULL,'2026-03-12',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Jose María de Arcas (jmac@ayco.es)',NULL,NULL,'2026-03-13',NULL,NULL,NULL,'Nosotros somos promotores no invertimos en proyectos de terceros.','Con feedback'),
  ('Arca','Angeles','David Gasso (dgasso@anchoreafi.com)',NULL,NULL,'2026-03-13','2026-05-11',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','ouribe@nemex.es (Registro plataforma Arca Token)',NULL,NULL,'2026-04-13',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','jagarciagodinez@gmail.com (Registro plataforma Arca Token)',NULL,NULL,'2026-04-13','11/05/2026 Invitación al desayuno',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','pedroxdt@gmail.com (Registro plataforma Arca Token)',NULL,NULL,'2026-04-15',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','tomasbet98@gmail.com ((Registro plataforma Arca Token))',NULL,NULL,'2026-04-20',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','yohania@conectaiberoamerica.com (Forbes)',NULL,NULL,'2026-04-23',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','''eduvigis@women4cyberspain.es''',NULL,NULL,'2026-04-23',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Carolina (''carolina.lira@alumni.esade.edu'') Forbes',NULL,NULL,'2026-04-23',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Alberto','Javier Acebron (ofrecido un 1,20%)',NULL,NULL,'2026-04-27','Seguimiento 12/06',NULL,NULL,'Enviada la información. Me comenta 12-jun que no tienen inversores de momento interasados','Con feedback'),
  ('Arca','Alberto','Andrés Garro (por parte de Javier Acebron)',NULL,NULL,NULL,'A través de Javier',NULL,NULL,NULL,'Sin contacto'),
  ('Arca','Alberto','Javier Saiz',NULL,NULL,'2026-04-27','2026-06-12',NULL,NULL,'Enviada la información','Con feedback'),
  ('Arca','Angeles','julio.perez@grupohelios.com Julio Grupo Helios',NULL,NULL,'2026-04-30','2026-05-11',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','jbarriosalejandro@gmail.com Alejandro Barrios',NULL,NULL,'2026-04-30','2026-05-11',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','jtausia@delunahotels.com CEO de Luna',NULL,NULL,'2026-04-30','2026-05-11',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Pedro Flames (Linkedin) pedroflames@grange-capital.com',NULL,NULL,'2026-05-04','11/05/2026 Invitación al desayuno',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','lalino@tenigla.com Luis Aliño (Linkedin)',NULL,NULL,'2026-05-04','11/05/2026 Invitación al desayuno',NULL,NULL,'Ahora mismo no vemos que sea el momento para invertir por dos puntos principalmente: (I) actualmente estamos inmersos en proyectos que nos exigen tiempo y equity  (II) estamos muy expuestos en estos momentos en residencial y queremos actuar en otras tipologías de activos.','Con feedback'),
  ('Arca','Angeles','Eliseo (Zriser)',NULL,NULL,'2026-05-04',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Chales de Ros (charles@geskaria.com)',NULL,NULL,'2026-05-05',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Angeles','Valentín Fernández valentin.fernandez07@gmail.com',NULL,NULL,'2026-05-06','11/05/2026 Invitación al desayuno',NULL,NULL,'De momento no invierte, queria inoformación','Con feedback'),
  ('Arca','Angeles','israte@gmail.com (Registro plataforma Arca Token)',NULL,NULL,'2026-05-12',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Andres','Juan David Peña',NULL,NULL,'2026-05-22','2026-06-08',NULL,NULL,'En validación por parte de su inversor','Con feedback'),
  ('Arca','Alberto','Paco R (Inversor Token) opacopaco@hotmail.com',NULL,NULL,NULL,'Email 2/06','2026-06-12',NULL,NULL,'Sin contacto'),
  ('Arca','Alberto','Hector  Tajahuerce (Inversor Xain)',NULL,NULL,NULL,'Enviado cuenta el 8/6',NULL,NULL,NULL,'Sin contacto'),
  ('Arca','Alberto','Pedro Anton y Cristobal',NULL,NULL,NULL,'Enviado despues de llamada por segunda vez 2/06',NULL,NULL,NULL,'Sin contacto'),
  ('Arca','Alberto','Olga Linden',NULL,'olga_linden@hotmail.com','2026-05-29','2026-06-02','2026-06-12',NULL,NULL,'Sin respuesta'),
  ('Arca','Alberto','Pablo Alonso',NULL,'Pabloalonso@msn.com','2026-05-29','2026-06-12',NULL,NULL,NULL,'Sin respuesta'),
  ('Arca','Alberto','Javier Bardaxi',NULL,NULL,NULL,NULL,NULL,NULL,'Invitada al evento de Andersen','Con feedback'),
  ('Arca',NULL,'Jose Manuel Ochoa',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca','Andrés','Alvaro Gil Delgado',NULL,NULL,NULL,NULL,NULL,NULL,'Invitada al evento','Con feedback'),
  ('Arca','Alberto','Luis Mezquita',NULL,NULL,NULL,NULL,NULL,NULL,'Invitada al evento de Andersen','Con feedback'),
  ('Arca','Alberto','Beatriz La Casa + 1',NULL,NULL,NULL,NULL,NULL,NULL,'Invitada al evento de Andersen','Con feedback'),
  ('Arca','Alberto','Pedro Antón',NULL,NULL,'2026-05-04',NULL,NULL,NULL,'Invitada al evento de Andersen','Con feedback'),
  ('Arca','Angeles','Juan Garcia Godinez',NULL,NULL,'2026-05-07',NULL,NULL,NULL,'Invitada al evento de Andersen','Con feedback'),
  ('Arca','Alberto','Andrés Arencibia',NULL,NULL,'2026-05-07',NULL,NULL,NULL,'Invitada al evento de Andersen','Con feedback'),
  ('Arca',NULL,'Bernhard',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca',NULL,'Javier Saiz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca',NULL,'Arantxa Saiz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca',NULL,'Jaime Guerrero',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca',NULL,'Antonio Oteros',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca',NULL,'Abogado Oteros',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca',NULL,'Daniel Leganés',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca',NULL,'Valentín Fernandez García',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Arca',NULL,'Olga Linden',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Alberto','Grupo Ibererebro',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'A la espera','Pendiente'),
  ('Villa Mallorca','Alberto','Amigo Alemán Berhanrd (Thorsten Gerbold)',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Pendiente se su agente inmobiliario Mallorca. Enviado comisiones','Pendiente'),
  ('Villa Mallorca','Alberto','Luis Martín Girado (Andersen)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Alberto','Vidal Israel (Ben Oldman)',NULL,NULL,NULL,NULL,NULL,NULL,'No interesado','Descartado'),
  ('Villa Mallorca','Alberto','Pablo Maye',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Alberto','Juan Urrutia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Alberto','Contacto Ibiza (Alemán y Ucraniano)',NULL,NULL,NULL,'Pendiente NDA',NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Andrés','Contacto Family Businees UK',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Andrés','Cheff amigo Andrés',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Andrés','FO Indio',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Andrés','FO Colombia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Andrés','FO Filipino',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Andrés','Fernando (Punto Ahorro)',NULL,NULL,NULL,NULL,NULL,NULL,'No interesado','Descartado'),
  ('Villa Mallorca','Andrés','Samir Lakkis',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Angeles','FO Alea',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Muchas gracias por tenernos en cuenta para la oportunidad, pero lo cierto es que en estos momentos no nos cuadra tanto por el ticket como por la tipología de proyecto.','Con feedback'),
  ('Villa Mallorca','Angeles','Diego Beatancour',NULL,NULL,'2025-09-12',NULL,NULL,NULL,'Segundo seguimiento hecho','Pendiente'),
  ('Villa Mallorca','Angeles','FO Herrecha',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Actualmente no estamos mirando propiedades en las islas para la familia','Con feedback'),
  ('Villa Mallorca','Angeles','Caboel',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'No es un tipo de activo en el que estemos interesados.','Descartado'),
  ('Villa Mallorca','Angeles','Grupo Timón',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Ahora mismo estamos 100% focalizados con el suelo que tenemos finalista pendiente de desarrollo, que conlleva un esfuerzo de capital importante y es donde tenemos centrada la estructura y los recursos del área de promoción inmobiliaria del grupo, estamos desarrollándolo por etapas','Pendiente'),
  ('Villa Mallorca','Angeles','Cosentino',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Por ubicación, tipología de activo y monto de inversión no encaja ahora mismo para nuestros criterios dentro del Family Office.','Descartado'),
  ('Villa Mallorca','Angeles','Mabel Capital',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Segundo seguimiento hecho','Pendiente'),
  ('Villa Mallorca','Angeles','Gaudir Mar',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Segundo seguimiento hecho','Pendiente'),
  ('Villa Mallorca','Angeles','FO Dispur',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Segundo seguimiento hecho','Pendiente'),
  ('Villa Mallorca','Angeles','FO NWG',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Segundo seguimiento hecho','Pendiente'),
  ('Villa Mallorca','Angeles','Fo Papanut',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Segundo seguimiento hecho','Pendiente'),
  ('Villa Mallorca','Angeles','Royal Met',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Segundo seguimiento hecho','Pendiente'),
  ('Villa Mallorca','Angeles','Casacuberta',NULL,NULL,'2025-09-11',NULL,NULL,NULL,'Segundo seguimiento hecho','Pendiente'),
  ('Villa Mallorca','Angeles','Jaime Cordorniu',NULL,NULL,'2025-10-03',NULL,NULL,NULL,'No interesado','Descartado'),
  ('Villa Mallorca','Angeles','Visse Capital',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Angeles','Gonzazo amigo Javier',NULL,NULL,NULL,'Enviado NDA',NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Alberto','Mauro keller Samiento (Contacto Luis Martin Girao)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Sin contacto'),
  ('Villa Mallorca','Andrés','Devesa',NULL,NULL,'2026-02-09',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Villa Mallorca','Angeles','Juan Rafael Ortiz',NULL,NULL,'2026-03-23','Enviado NDA y firmado. Enviado deck',NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Angeles','Sebastián Bernasconi','Eurogaza',NULL,'2025-01-20','2026-02-12','2026-02-20','2026-03-10',NULL,'Sin respuesta'),
  ('Eurogaza','Angeles','Buenasvista (Jorge)','Eurogaza',NULL,'2025-01-20','2026-01-27',NULL,NULL,'Muchas gracias por la oportunidad pero no encajaría con la estrategia del Fondo, es un proyecto de turn around y buscamos cosas más consolidadas.','Descartado'),
  ('Eurogaza','Alberto','Javier Bardaxi','Eurogaza',NULL,'2025-01-20',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Alberto','Manuel Torres','Eurogaza',NULL,'2025-01-20',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Angeles','Bridge Point','Eurogaza',NULL,'2026-02-03',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Andrés','Adarve','Eurogaza',NULL,'2026-02-03',NULL,'No avanzan con la oportunidad',NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Angeles','SUMA Capital','Eurogaza',NULL,'2026-02-03',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Angeles','Papanut','Eurogaza',NULL,'2026-02-03','2026-02-09',NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Angeles','Abac Capital','Eurogaza',NULL,'2026-02-09',NULL,NULL,NULL,'La verdad que a nivel financiero se nos queda pequeño, ya que invertimos en compañías de +2m EBITDA (además del EBITDA negativo de 2024).','Con feedback'),
  ('Eurogaza','Angeles','Cosentino','Eurogaza',NULL,'2026-02-04',NULL,NULL,NULL,'Ahora mismo no vamos a tener capacidad.','Con feedback'),
  ('Eurogaza','Angeles','Inderhabs','Eurogaza',NULL,'2026-02-04',NULL,NULL,NULL,'Me temo que el sector de transformación de vehículos sanitarios y de emergencia no encajaría con nuestro enfoque de inversión actual.','Descartado'),
  ('Eurogaza','Angeles','Oquendo Capital','Eurogaza',NULL,'2026-02-04',NULL,NULL,NULL,'No avanzan','Descartado'),
  ('Eurogaza','Angeles','Grupo Santa Marta','Eurogaza',NULL,'2026-02-04','2026-03-19',NULL,NULL,'Enviado NDA','En proceso'),
  ('Eurogaza','Angeles','Aurica Capital','Eurogaza',NULL,'2026-02-04',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Alberto','Bernhard Schmidt','Eurogaza',NULL,'2026-02-04',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Andrés','Devesa','Eurogaza',NULL,'2026-02-09',NULL,NULL,NULL,NULL,'Sin respuesta'),
  ('Eurogaza','Andrés','Moira','Eurogaza',NULL,'2026-03-05','Enviado perfil ciego',NULL,NULL,NULL,'Sin respuesta'),
  ('Team PLV','Andres','Adarve',NULL,NULL,'2026-02-03',NULL,NULL,NULL,'No avanzan con la oportunidad','Descartado'),
  ('Zappas','Angeles','Impact Bridge','Operación hipotecaria',NULL,'2025-10-21','no encaja con las características de nuestro fondo.',NULL,NULL,NULL,'Sin respuesta'),
  ('Zappas','Angeles','Spirius','Operación hipotecaria',NULL,'2025-10-21','No podemos continuar con su estudio debido a los largos plazos que exige la operación para tener un mínimo retorno.',NULL,NULL,NULL,'Sin respuesta'),
  ('Zappas','Alberto','CA Indosuez Wealth','Operación hipotecaria',NULL,'2025-10-21','A la espera',NULL,NULL,NULL,'Sin respuesta'),
  ('Zappas','Angeles','Mirabaud','Operación hipotecaria',NULL,'2025-10-21','Nos pide información completa. Se le evía el 22 de octubre',NULL,NULL,NULL,'Sin respuesta'),
  ('Zappas','Alberto','BBVA','Operación hipotecaria',NULL,NULL,'En riesgos y a  la espera',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Alberto','Bankinter','Operación hipotecaria',NULL,NULL,'No entran',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Angeles','Groupama Asset','Operación hipotecaria',NULL,'2025-10-22','Pendiente',NULL,NULL,NULL,'Sin respuesta'),
  ('Zappas','Alberto','Caixa','Operación hipotecaria',NULL,NULL,'La sucursal no quiere darlo',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Angeles','Oquendo Capital','Operación hipotecaria',NULL,'2025-10-22','No encaja en la estrategia de financiación de los nuevos fondos de que disponemos.',NULL,NULL,NULL,'Sin respuesta'),
  ('Zappas','Angeles','AltamarCAM Partners','Operación hipotecaria',NULL,'2025-10-23','Nos interesan más los proyectos de equity.',NULL,NULL,NULL,'Sin respuesta'),
  ('Zappas','Alberto','Bankinter','Operación hipotecaria',NULL,NULL,'No entran',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Alberto','Sabadell','Operación hipotecaria',NULL,NULL,'Ha pasado el pre-comité del viernes 31. Preparando rpesentación a riesgos',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Alberto','Santander','Operación hipotecaria',NULL,NULL,'A la espera',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Alberto','Unicaja','Operación hipotecaria',NULL,NULL,'Presentada a riesgos',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Alberto','Ibercaja','Operación hipotecaria',NULL,NULL,'Tardan 2 meses en montar la operación',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Alberto','Kutxa Bank','Operación hipotecaria',NULL,NULL,'A la espera',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Andres','Deustsche Bank','Operación hipotecaria',NULL,NULL,'La operación les pareció interesante pero no hacen hipoteca sobre suelo rural y pedían otro activo diferente para garantizar la operación',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Andres','ING','Operación hipotecaria',NULL,NULL,'La operación es muy pequeña para ellos',NULL,NULL,NULL,'Sin contacto'),
  ('Zappas','Andres','Caja Rural del Sur','Operación hipotecaria',NULL,NULL,'La operación es muy grande para ellos, y con la limitación de que hacen desembolso por tramos',NULL,NULL,NULL,'Sin contacto');